### ISSUE TITLE
bcit-ci/codeigniter-website

### ISSUE THREAD

**Issue by jamesonyemi** [bcit-ci/codeigniter-website#115]
An uncaught Exception was encountered

Type: Error

Message: Class 'Github\Client' not found

Filename: C:\xampp\htdocs\codeigniter-website\application\libraries\Github_api.php

Line Number: 26

Backtrace:

File: C:\xampp\htdocs\codeigniter-website\application\core\MY_Controller.php
Line: 28
Function: library

File: C:\xampp\htdocs\codeigniter-website\application\controllers\Welcome.php
Line: 15
Function: __construct

File: C:\xampp\htdocs\codeigniter-website\public\index.php
Line: 277
Function: require_once

**Comment by jamesonyemi** [comment]
I got this error after I fork and clone this project.
Are there anything I am missing.

**Comment by Rodrigo54** [comment]
The error may have occurred because composer dependencies might not be installed

Try this:
1. Install the composer: https://getcomposer.org/
1. Open the terminal in the project root folder
1. Put the composer install command on the terminal
1. And see if it works
