### ISSUE TITLE
codeigniter forum registration problem

### ISSUE THREAD

**Issue by raku** [bcit-ci/codeigniter-website#19]
Hello,

I'm trying to register on codeigniter forum but when i push submit registration button nothing happens.
I'm using Opera and Internet Explorer.
Can you check please?

Thanks!
![forum-codeigniter](https://cloud.githubusercontent.com/assets/158101/6770076/79da4a6a-d0bd-11e4-8742-7bf04c5b6b74.jpg)

**Comment by jim-parry** [comment]
Github is for bugs, not support.
Send me an email with your details, please ... jim_parry@bcit.ca
