### ISSUE TITLE
Encouraging HTTPS

### ISSUE THREAD

**Issue by jim-parry** [bcit-ci/codeigniter-website#32]
We have arranged for CDN & SSL support of our server, and should start encouraging https:// links on our website. Some of these might be addressed as "//" links, while others might need the "https://" prefix. 

Relative links in the site should redirect correctly automatically, but there are a number of hard-coded ones :(

The main website can be accessed using https, but trying to do that with the forum is giving me a bit of grief.

**Comment by jim-parry** [comment]
This is progressing slowly, as I adjust bits & pieces of the site and forum, and the apache configuration. About 22% of the server traffic is now using SSL.

**Comment by jim-parry** [comment]
I am going to drop this as an issue. I need to proceed slowly & make sure I don't mess up the CDN & forum operation. You should see more & more of the site being served over SSL :)

**Comment by zhanghongyi** [comment]
Although it is a closed issue, I found that in `composer.json` the homepage address is not updated yet. This should be an easy fix and would not affect security issues. Should this be updated?

**Comment by jim-parry** [comment]
yes, it should, thanks

**Comment by zhanghongyi** [comment]
ok, will pull request if you haven't done it yet.
