### ISSUE TITLE
Github buttons not showing?

### ISSUE THREAD

**Issue by zhanghongyi** [bcit-ci/codeigniter-website#52]
When I loaded the official website tonight, I found that the style of github buttons is not shown. I tried with three main browsers, but got no luck. But when I looked into the source codes, it seemed nothing was wrong as far as I can tell. And when I pulled the latest changes and run locally, it turned out to be fine. 

Screenshot:
![screen shot 2015-10-08 at 21 44 00](https://cloud.githubusercontent.com/assets/3772296/10386002/ef387fb2-6e05-11e5-8ba0-3125fa0d9c89.png)

I wonder if others has the same issue or it only happened to me unluckily?

**Comment by jim-parry** [comment]
Oh my - I see the same thing on one of my computers, but not on the other.
Browser cache issue? Need to dog further!

**Comment by jim-parry** [comment]
looks like font-awesome icons not loading, while glyphicon ones do

**Comment by jim-parry** [comment]
template seems to be missing 2 links ... fixing

**Comment by jim-parry** [comment]
Fixed it ...

**Comment by jim-parry** [comment]
Thank you, honygi, for pointing this out!

**Comment by zhanghongyi** [comment]
quick fix, cool!
