### ISSUE TITLE
Class 'Github\Client' not found

### ISSUE THREAD

**Issue by shihasck** [bcit-ci/codeigniter-website#96]
Once I run this project it showing me this error:

> An uncaught Exception was encountered
> 
> Type: Error
> 
> Message: Class 'Github\Client' not found
> 
> Filename: /Applications/MAMP/htdocs/website/application/libraries/Github_api.php
> 
> Line Number: 26
> 
> Backtrace:
> 
> File: /Applications/MAMP/htdocs/website/application/core/MY_Controller.php
> Line: 65
> Function: library
> 
> File: /Applications/MAMP/htdocs/website/application/controllers/Welcome.php
> Line: 53
> Function: __construct
> 
> File: /Applications/MAMP/htdocs/website/index.php
> Line: 277
> Function: require_once

**Comment by jim-parry** [comment]
It sounds like the Guzzle package hasn't been installed. Did you do a composer install/update inside the project before running it?

**Comment by shihasck** [comment]
No I didn't do nothing. So how can I install Guzzle package?

**Comment by jim-parry** [comment]
Assuming you have composer installed, execute the "composer install" from a command prompt, in the root of your project. The dependencies are built in to composer.json. If you are using an IDE, it usually has a "composer install" accessible from a menu.

**Comment by shihasck** [comment]
I just execute "composer install" and I think it got installed. But still the same error :(

**Comment by jim-parry** [comment]
Can you PM me on our IRC channel? I think that would be faster than trying to resolve this via email / issue comments

**Comment by shihasck** [comment]
Can you please tell me how to do that in IRC channel. I have no idea about that !!!

**Comment by jim-parry** [comment]
If you have an IRC client, point it at #codeigniter
If you don't, you can use http://webchat.freenode.net/?channels=%23codeigniter&uio=d4%22
If you are not comfortable with IRC, check http://workaround.org/getting-help-on-irc

If you join the channel with the same name as here, I can trigger a private conversation with you

**Comment by shihasck** [comment]
@jim-parry I joined with same name(shihasck) on #codeigniter channel

**Comment by shihasck** [comment]
@jim-parry  I tried installing the composer again and I fixed it now. Thanks 👍

**Comment by jim-parry** [comment]
I noticed, but only a minute before you left the channel, sorry :(
You said there that you "fixed it"? Can you share what the solution was? Do I need to update the readme on this repo?
